name: Minha primeira linha de montagem

on:
  push:
    branches: [ main ]
jobs:
  build-e-teste:
    runs-on: ubuntu-latest

    steps:
    - name: 1. pegar o chassi do carro (código-fonte)
      uses: actions/checkout@v3
      
    - name: 2. estação de build (montagem)
      run: echo "construindo o projeto... Verificando se todas as peças se encixam!"

    - name: 3. estação de testes (controle de qualidade)
      run: echo "rodando os testes automatizados... Verificando se a porta abre e fecha!"
