name: minha primeira linha de montagem

on:
  push:
    branches: [ main ]

jobs:
  build-e-teste:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Pegar o chassi do carro (Código-fonte)
        uses: actions/checkout@v3

      - name: 2. Estação de build (Montagem)
        run: echo "Construindo o projeto... Verificando se a porta abre e fecha!"
